### PR TITLE
Change logging from context logger to stdout + add missed stderr logging from stream logging

### PR DESCRIPTION
**Pull request by yassineazzouz**
Hi @frozenice ,

I found out that the errors are not displayed in stream logs if the ansible playbook fails, so I added a redirection so that stderr get redirected to stdout for stream logging just like file logging. I also changed the logging from context logger to to stdout, I thought this will be better since the context logger will print ansible output in rendeck.log too so it will print lot of logs and make debugging a bit difficult, whereas stdout will print logs only in the screen. 

Please let me know your thoughts,
Thanks,

### CODE REVIEW

**Comment by yassineazzouz** [comment]
Sorry for the missing email in my commit, just found out that I was using a bad username.

**Comment by frozenice** [comment]
Right, good catch. I guess you can also remove the `logger` vars, as they aren't used anymore.

I think the non-stream mode can be removed from AnsibleRunner, too, as `getOutput` isn't called by anything important.

**Comment by yassineazzouz** [comment]
Thanks,I'm working on a second PR for that.

**Comment by yassineazzouz** [comment]
Hi @frozenice ,

Sorry took me some time to finalize and properly test the code. I addressed three issues in this second PR:

1- I did some code clean up, to better handle exceptions, on error I put the error message in ansible exception from stdout and throw it to the calling function which then return it to the UI, I also used finally block to make sure temporary files and Streams get properly cleaned up on failure.

2- As you mentioned I agree that trying to parse the Output as json will not work with higher logging levels so I removed that part and used Stream logging for all Tasks. I also used a better approach for displaying logs in Rundeck web UI  using a Stream copy thread which makes logs display lot faster.

3- I added support for interrupting jobs using the Rundeck WebUI. previously when we press "kill" nothing happens so I added InterruptionException handling to properly kill the ansible jobs when the kill button is hit.

Please let me know your thoughts.
Thanks,

**Comment by yassineazzouz** [comment]
Hi @frozenice ,
Did you have some time to take a look at this ?
Thanks,

**Comment by yassineazzouz** [comment]
The only annoying thing here is when using Playbook Node Steps with parallel threads (>1), logs are mixed in stdout, so it is a bit difficult to read. The good thing is rundeck offers the possibility to display logs per node so we still can see logs by node which kind of resolve the problem. 
My point is from my opinion we don't really have to buffer logs before displaying them in the UI so that we print only a complete task log (which is of course more readable but harder to implement ) since we need to parse the Process output logs and recognize the beginning and the end of a module log before printing it (which may be complicated using different logging levels DEBUG vs INFO ...), I think we can just do a simple thread stream copy, which will would not know the begging or end of a module nor its format. Display can jump from one process log to the other during the execution. But the rundeck, by node logs can still provide a very understandable and clean log, and we still can benefit from the fast logging (since logs are not buffered).

**Comment by frozenice** [comment]
Sorry for the late response, this looks good, just needs a rebase / conflict resolve.

Letting Rundeck do the grouping per Node seems like a good plan.

P.S.: Nice job with the 1.3.1 release, looks good! :)

P.P.S.: I remembered a thing I wanted to put into the CONTRIBUTING file: My idea was to keep the `AnsibleRunner` wrapper as a "stand-alone" class, with no deps on Rundeck or anything else. In this way it could be used by others, who want to run Ansible from Java/Groovy, as it has some nice convenient features. I don't know how isolated it is now, maybe we can add it as a goal for later?

**Comment by yassineazzouz** [comment]
Thanks @frozenice ,

I totally agree, separating the Ansible Runtime from the Rundeck components makes perfect since. I think the Rundeck Jobs share a lot of features in common, and probably right now the easiest way to share code across different types of Jobs ( like NodeSteps and WorkflowSteps .... ) is to make it part of the AnsibleRunner since it affects all Jobs types. I could be wrong but probably a good idea is to create a generic class that Handle all common jobs features like:
- Common Argument Parsing 
- Logging
- Error Handling
  ....
  That way we can have the GenericAnsibleStep handle all common Parts of a rundeck Job and avoid code duplication and keep the AnsibleRunner as a Stand Alone Ansible executor.

I will Take care of refactoring the code for the current PR (remove the rundeck logger for the AnsibleRunner) and resolve conflicts. If you like my suggestion we can start working on a separate PR for it :).

**Comment by frozenice** [comment]
Sounds good! :+1:
The classes offer plenty of opportunity for refactoring.

**Comment by yassineazzouz** [comment]
Hi @frozenice ,

I did some code cleaning and resolved conflicts, The idea as you mentioned above is to decouple the  ansible runner from the rundeck Tasks. So I created a new Logging class that handle real time logging from the process output to a listener. The listener Factory and listener interface will allow an easy definition of multiple types of listeners : file/stdout logging or interface with other logging systems, so rundeck uses the AnsibleRunner with the default System.out listener and other implementations are free to define their own. Please let me know you thoughts :).

**Comment by frozenice** [comment]
LGTM! I didn't test it, but I assume you did. ;) Feel free to merge when you're good to go.

**Comment by yassineazzouz** [comment]
Great :) Thanks.

**Pull request merged**
