### PR TITLE
Add "disable ansible limit" to the playbook step.

### PR DESCRIPTION
**Pull request by ltamaster**

### CODE REVIEW

**Comment by frozenice** [comment]
Can you explain this change and the motivation behind it a bit?

**Comment by ltamaster** [comment]
For example, if you want to run a playbook locally (Rundeck server) without defined the node on the job (I mean without dispatching the job/playbook to a list of nodes).

**Comment by mcassaniti** [comment]
I personally see two potential use cases for disabling/changing the limit parameter:

1. When running a task as a workflow step and the nodes setting of a job is set execute locally, you would execute the task locally rather than using `--limit <rundeck_hostname>`
1. When running a playbook or an inline playbook the list of target hosts is already defined within the playbook

Your solution seems to target the second use case. For the first use case I've been adding `--limit localhost --connection local` to the Ansible arguments.

I might leave @frozenice to take a look and decide on approving. I'm a bit hesitant to start using that power just yet. I haven't tested your changes in a test environment either.

**Comment by arvy** [comment]
@ltamaster Great fix! I've been trying to figure out how to hack this. I have applied your commit in my fork. I hope it gets approved.
I also submitted a little tweak I made: #177

**Review by mcassaniti — CHANGES_REQUESTED** [review]
Can you also add this to the inline Ansible playbook? If you can get that added I can approve.

**Comment by ltamaster** [comment]
@mamercad  I added it to the inline playbook.

Luis

**Review by mcassaniti — APPROVED** [review]

**Comment by juresaht2** [comment]
For anyone else stuck with the same problem as me: This option is only present on Workflow Steps and is not present on Node Steps.

**Pull request merged**
