### PR TITLE
Dedicated log filter plugin to capture the output of ansible set_stats module

### PR DESCRIPTION
**Pull request by Simon-cto**
This plugin eases the capture of data from an ansible playbook (inline or not) step by capturing the resulting log output of the set_stats module, parsing it as a json object and creating the corresponding data context variables.

The plugin works like so:
image

image

image

image

### CODE REVIEW

**Comment by Simon-cto** [comment]
For some reason, when I build the ansible plugin using gradle on Windows the plugin is available but not when I build it on RHEL.
I don't get any error during the gradle build process.

Any idea why?

**Comment by fdevans** [comment]
@Simon-cto Do you get any error messages when building that you can share with the team?  Any other symptoms?

Thanks so much for the PR though, this is a great addition.  Can you work on it in "Draft" then move to "Ready for Review" when you're ready for the team to check it out?

**Comment by Simon-cto** [comment]
> @Simon-cto Do you get any error messages when building that you can share with the team? Any other symptoms?
> 
> Thanks so much for the PR though, this is a great addition. Can you work on it in "Draft" then move to "Ready for Review" when you're ready for the team to check it out?

Nevermind, I retested the build from Linux today and it works as expected.

I'm not sure what happened yesterday but I can't reproduce it.

I think it's ready for review.


Thanks

**Comment by ltamaster** [comment]
@Simon-cto can you share the job you used to test it?

**Review by ltamaster — APPROVED** [review]

**Comment by Simon-cto** [comment]
> @Simon-cto can you share the job you used to test it?

Here is the job definition is json format
[Test_set_stats (1).json](https://github.com/rundeck-plugins/ansible-plugin/files/13052478/Test_set_stats.1.json)

**Pull request merged**
