### PR TITLE
Add Vault file/password/key-storage to RM/NE/FC

### PR DESCRIPTION
**Pull request by ltamaster**
Add Vault file/password/key-storage to ResourceModel/NodeExecutor/File Copier, so you can use encrypting ansible-vault files.

### CODE REVIEW

**Review by mcassaniti — APPROVED** [review]

**Comment by mcassaniti** [comment]
I've merged this, but I'd also like you to extend to Workflow steps. In hindsight I should've requested changes before approving.

**Comment by ltamaster** [comment]
Hey @mcassaniti, this already exists on workflow step, in this PR I am extending that functionality to ResourceModel/NodeExecutor/File Copier

**Comment by mcassaniti** [comment]
I took a look at the latest release and noted that the vault options for a Resource Model vs a Node Executor are different. I think I'll need to unify the options across the plugin at some point and group the vault options. In short, leave it with me.

**Comment by ltamaster** [comment]
@mamercad what difference did you find?
For Resource Model, it is not possible to access to the key storage, maybe that is the difference that you saw.

**Comment by mcassaniti** [comment]
I'm betting that was why I saw a difference.

**Comment by mamercad** [comment]
Hrm, I'm not sure why I'm in this conversation?

**Comment by ltamaster** [comment]
Sorry @mamercad my mistake

**Pull request merged**
