### PR TITLE
Add working directory / base directory option

### PR DESCRIPTION
**Pull request by mcassaniti**
This PR is unfortunately **untested** since I don't know how to build the code. I'm mainly after feedback at this point. It should be a fix for #47 even though the issue was closed.

The primary purpose is to allow a base directory per workflow step to be set that the Ansible repository is stored in. A job could use multiple repositories, or use a repository that is not in /etc/ansible. The repository path needs to be set when using custom Ansible modules and plugins that are stored with the repository. I believe referencing roles will also be an issue.

### CODE REVIEW

**Comment by frozenice** [comment]
Is this still relevant / needed?

**Comment by mcassaniti** [comment]
Absolutely this is required. I've now managed to build the plugin and I've got it running within Rundeck for our production environment. We have custom Ansible modules within our Ansible directory, along with some custom action plugins. Without setting the base directory the modules and plugins are not accessible in a playbook or a role.

I apologise that there's several commits for this feature.

**Review by frozenice — APPROVED** [review]

**Comment by frozenice** [comment]
Thanks! I added you as a collaborator.

> I apologise that there's several commits for this feature.

That is perfectly fine and often easier to grasp then one huge commit.

**Comment by mcassaniti** [comment]
Much appreciated. Don't know how much assistance I'll be as a collaborator, but then again I may just eat those words.

**Pull request merged**
