### PR TITLE
Feat pass inventory vars

### LINKED ISSUE #214: Passing node property values to an Ansible playbook
I have Rundeck configured with EC2 plugin, this way I can retrieve all my EC2 instances and define jobs that run commands on those instances.
This works fine for usual scripting, now I wanted to use Ansible to e.g. start/stop instances. For that to work I need to pass at least EC2 region and instance ID. I have this information in the Rundeck node but I don't know how to pass it to the Ansible playbook, precisely I don't know how to define a variable that will be evaluated to the instanceId value.

This is my playbook:

```
---
- name: Start  instances
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: Start the feature instances
      ec2:
        instance_ids: '{{ instanceId }}'
        region: '{{ region }}'
        state: running
        wait: True
```

I tried to define extra variables in different ways but nothing seems to work.

```
{
  "region": "eu-center-1",
  "instanceId":  "{{ node.instanceId }}",
}
``` 

I am using Rundeck 3.0.8 with the Ansible plugin 2.5.0

### LINKED ISSUE #230: How to pass host variables from ansible inventory into rundeck and back to ansible?
Rundeck 3.0.11 and Ansible 2.7.5 and python 2.7 on CentOS 7.6.1810 to automate tasks on network devices, like Cisco IOS switches.

In Ansible >=2.5 it appears the best method to use is "connection: network_cli" which requires setting the OS type using "ansible_network_os=ios" (for Cisco IOS).

I have that variable declared for my host in my source Ansible inventory file, but it doesn't translate through into Rundeck. Gather Facts under Node Sources doesn't work to auto-determine, since these devices are not servers.

Under a given workflow step I can feed that variable in using "Extra Ansible arguments" and passing "-e ansible_network_os=ios". And that works. But would require setting that on every job, and every job then being OS-specific.

Is there a more elegant way of doing this? I know the OS type ahead of time for everything. Being able to add this info into the source Ansible inventory file seems like the best approach, either per device or using group variables.

Thank you!

### LINKED ISSUE #273: [Q] Custom attributes from fact
Hello, 
Is it possible to use ansible fact as a custom attribute? I would like to see my attribute (fact_download_speed_in_bytes_per_second) in the node overview.

```yaml
  - name: Set persistent fact
    set_fact:
      fact_download_speed_in_bytes_per_second: download_speed
```

### PR DESCRIPTION
**Pull request by ggwena**
Pass inventory vars to generated inventory

- AnsibleResourceModelSource: Add parameter 'import inventory vars'
- AnsibleResourceModelSource: Add parameter 'ignore inventory vars'
- AnsibleResourceModelSource adds all Ansible Vars as attributes
- AnsibleInventory passes Node attributes in generated inventory

### CODE REVIEW

**Comment by mschwab-bhs** [comment]
Hey, we would also like to use these feature. Is it possible to merge it into the master branch?

**Comment by FlorianL-Git** [comment]
Same for us, is there any reason why this is not getting merged? @frozenice 

Having the possibility to specify ansible inventory vars as node attribute would greatly improve our work

**Comment by frozenice** [comment]
@FlorianL-Git (and @mschwab-bhs) No special reason except we aren't using this and I have no time / knowledge to look at this. I invited you both as collabs, so you can merge and release (see `CONTRIBUTING.md` for how to release, I hope this still works) if you think this is good. :)

**Review by tehCrush — COMMENTED** [review]
i reviewed the code and built the results to test it, it passes the build / test and works on rundeck 4.1.0

Modifications to AnsibleRunner, AnsibleRunnerBuilder, AnsiblePlaybookWorkflowStep, AnsibleNodeExecutor, AnsibleModuleWorkflowStep, PropertyResolver and AnsibleException seem to be unneeded as no code was actually changed, just replaced?  

edit: premature submit

**Comment by lukasertl** [comment]
This feature would be very much appreciated.

**Review by ltamaster — APPROVED** [review]

**Pull request merged**
