### PR TITLE
add 'options' to Ansible jobs

### PR DESCRIPTION
**Pull request by mamercad**
I'm not super good with Java, please look this over carefully :)

### CODE REVIEW

**Comment by frozenice** [comment]
Thanks! That was pretty much like a wanted to do it. :)

I made some modifications and added it to the other components.

Landed in [v1.2.0](https://github.com/Batix/rundeck-ansible-plugin/releases/tag/1.2.0).

**Comment by mamercad** [comment]
Sweet, thanks.

**Comment by aswath110** [comment]
Hi frozenice thanks for ur awesome plugin.. I want some help from you, i am not able to understand how i get the input of the values which i set in options from rundeck inside ansible playbook..

**Comment by frozenice** [comment]
Hi @aswath110, do you mean the options you create yourself in the Rundeck UI when you configure a job?

**Comment by aswath110** [comment]
Yes.. which i create from Rundeck UI.. I think ur working on this feature i think i have asked in wrong thread

**Pull request merged**
