### PR TITLE
[WIP] Inline inventory

### PR DESCRIPTION
**Pull request by pieterdp**
Fix for #201

### CODE REVIEW

**Review by mcassaniti — COMMENTED** [review]
Perhaps a slight re-work.

Specified the ansible inventory .... It is also possible to provide an inventory _inline_ to a job. The default is /etc/ansible/hosts.

**Comment by mcassaniti** [comment]
Thank you for your PR. They're always welcome. I did however want to check I'm thinking of the same use case. Are you intending to have a user provide a per-job inventory by manually entering the information, or are you setting the inventory in the job configuration?

In either case, this PR seems to address the case when the Rundeck inventory is not used at all to determine which nodes to target. The `file copier`, `node executor`, `inline workflow node` and `workflow node` plugins all rely on the Rundeck inventory. I don't think it wise to provide a separate inventory to these plugins. The `module workflow`, `inline workflow` and `workflow` plugins do make some sense here.

**Comment by pieterdp** [comment]
The idea is to provide an Ansible inventory, independent of the Rundeck inventory, inline (so per job, in the job configuration) for use cases where you want the user to modify the inventory by having access to the Rundeck instance, but not to the underlying file system.

I agree that it is not very useful for file copier, node executor, inline workflow node and workflow node; I'll rework the PR.

**Comment by FloThinksPi** [comment]
May we considder beeing able to also overlay the inventories ?

Usecase: 
As a Job developer, i want to group my Servers for use in an Ansible Playbook but the specific groups used are only needed for this single Job. I want to group my Servers or define them for this job, without changing the global Inventory definition which would introduce unnececary groups to all Playbooks while only needed by one. But i also want to keep variables/information defined in the global inventory.

CLI Equivalent:
ansible-playbook -i localinventory -i /etc/ansible/hosts myplaybook.yml

Ansible supports overlaying Inventorys. It will automatically merge them.
https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html

I am not sure if that would be possibe with the current WIP implementation.
In the Code of the AnibleRunnerBuilder the Inventory gets returned once so i think it is either inline or global. We could append both files ourself depending on a checkbox state.

**Comment by ltamaster** [comment]
replaced by  #318

**Pull request closed without merging**
