### PR TITLE
Added Inline Step

### PR DESCRIPTION
**Pull request by DerekTBrown**
I added a step which allows for adding an inline `.yml` playbook.  There are a couple of reasons why this is preferable in the long run:

* For many users it is a pain to create individual playbooks for each logical "step".  This leads to massive playbooks, which prevents rundeck from handling task-level errors.

* Enables users without access to the rundeck file system to add playbooks.

* Easier and more stable syntax to use than modules

### CODE REVIEW

**Comment by frozenice** [comment]
Neat! I will take a look later.
Some docs would be nice. :)

**Comment by DerekTBrown** [comment]
@frozenice Not really sure it needs documentation.  It is identical to the existing step, save that it uses Ace Editor as opposed to a file.

**Comment by frozenice** [comment]
Yeah, I meant it more in the sense of "document that this feature exists", a sentence mentioning the possibility to chose between file and inline in the README.

**Comment by frozenice** [comment]
Merged, also added you as a collaborator, welcome! Feel free to add more features and / or squish bugs. :)

**Comment by frozenice** [comment]
Released in [2.1.0](https://github.com/Batix/rundeck-ansible-plugin/releases/tag/2.1.0), updated [docker image](https://github.com/Batix/rundeck-ansible-plugin/blob/master/docker-container.md).

**Comment by DerekTBrown** [comment]
Thanks!!

**Pull request merged**
